CREATE DATABASE customer_behaviour;
USE customer_behaviour;
SELECT * FROM customer;

Q1. What is the total revenue generated by male vs. female customers?
    SELECT gender,SUM(purchase_amount) as total_revenue
	FROM customer
	WHERE gender IN('Female','Male')
	GROUP BY gender;

Q2. Which customers used a discount but still spent more than the average purchase amount?
    SELECT customer_id,discount_applied
	FROM customer
	WHERE discount_applied ='Yes'
	AND purchase_amount>(
	SELECT AVG(purchase_amount) as avg_purchase
	FROM customer
	);

Q3. Which are the top 5 products with the highest average review rating?
    SELECT top 5 item_purchased,AVG(review_rating) as total_review_rating
	FROM customer
	GROUP BY item_purchased
	ORDER BY total_review_rating DESC;

Q4. Compare the average purchase amounts between Standard and Express Shipping.
    SELECT shipping_type,AVG(purchase_amount) as avg_purchase
	FROM customer
	WHERE shipping_type IN('Standard','Express')
	GROUP BY shipping_type

Q5. Do subscribed customers spend more? Compare average spend and total revenue between
    subscribers and non-subscribers.
	SELECT 
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
    FROM customer
    GROUP BY subscription_status;

Q6. Which 5 products have the highest percentage of purchases with discounts applied?
    SELECT TOP 5 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
    FROM customer
    GROUP BY item_purchased
    ORDER BY discount_percentage DESC;

Q7. Segment customers into New, Returning, and Loyal based on their total number of
    previous purchases, and show the count of each segment.
    SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(customer_id) AS customer_count
FROM customer
GROUP BY 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END;
	select * from customer
Q8. What are the top 3 most purchased products within each category?
    SELECT *
    FROM (
    SELECT 
        item_purchased,
        category,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY item_purchased, category
    ) t
    WHERE rn <= 3;
	
Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
    SELECT 
    subscription_status,
    COUNT(*) AS customer_count
    FROM customer
    WHERE previous_purchases > 5
    GROUP BY subscription_status;

Q10. What is the revenue contribution of each age group?
    SELECT 
    subscription_status,
    COUNT(*) AS customer_count
    FROM customer
    WHERE previous_purchases > 5
    GROUP BY subscription_status;


